In [11]:
a=int(input("Enter First number: "))
b=int(input("Enter second number: "))
if a*b > 1000:
    print(a+b)
else:
    print(a*b)

Enter First number:  11
Enter second number:  100


111


In [12]:
import numpy

In [13]:
firstArray = numpy.empty([4,2], dtype = numpy.uint16)

In [14]:
print("Printing Array")
print(firstArray)

Printing Array
[[50068 28456]
 [38353 52462]
 [20304   576]
 [ 8419 21796]]


In [15]:
print("Array dimensions are " , firstArray.ndim)

Array dimensions are  2


In [16]:
array2 = numpy.arange(100,200,10).reshape((5,2))

In [17]:
array2

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [21]:
array3 = numpy.array([[11,22,33],[44,55,66],[77,88,99]])

In [22]:
array3

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [23]:
newArray = array3[...,1]
print(newArray)

[22 55 88]


In [30]:
array4 = numpy.arange(10,34,1).reshape((8,3))
array4

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [31]:
subarrays = numpy.split(array4, 4)
print(subarrays)

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [46]:
listone = numpy.arange(3,22,3)
listtwo = numpy.arange(4,29,4)
oddelements = listone[1::2]
evenelements = listtwo[0::2]

In [48]:
listthree = list()

In [49]:
listthree.extend(oddelements)
listthree.extend(evenelements)

In [3]:
listthree

NameError: name 'listthree' is not defined